import { FaHome, FaSquare } from "react-icons/fa";

export const data = [
  {
    unitID: "13A-01",
    name: "Southlink",
    bedroom: 1,
    bathroom: 1,
    size: 452,
    parkingSlot: 0,
    status: "rented",
    price: "1500",
    url: "https://picsum.photos/400/300",
  },
  {
    unitID: "12-02",
    name: "Southlink",
    bedroom: 2,
    bathroom: 1,
    size: 500,
    parkingSlot: 1,
    status: "available",
    price: "1800",
    url: "https://picsum.photos/400/300",
  },
  {
    unitID: "11-10",
    name: "Southlink",
    bedroom: 2,
    bathroom: 2,
    size: 680,
    parkingSlot: 1,
    status: "available",
    price: "2200",
    url: "https://picsum.photos/400/300",
  },
  {
    unitID: "20-09",
    name: "Southview",
    bedroom: 2,
    bathroom: 1,
    size: 550,
    parkingSlot: 1,
    status: "available",
    price: "1800",
    url: "https://picsum.photos/400/300",
  },
  {
    unitID: "05-03",
    name: "Southview",
    bedroom: 1,
    bathroom: 1,
    size: 500,
    parkingSlot: 1,
    status: "rented",
    price: "1500",
    url: "https://picsum.photos/400/300",
  },
  {
    unitID: "09-01",
    name: "KLGW",
    bedroom: 2,
    bathroom: 1,
    size: 550,
    parkingSlot: 1,
    status: "available",
    price: "2200",
    url: "https://picsum.photos/400/300",
  },
];
export const navBar = [
  {
    id: 1,
    name: "Home",
    url: "/",
    icon: <FaHome />,
  },
  {
    id: 2,
    name: "About",
    url: "/about",
    icon: <FaSquare />,
  },
  {
    id: 3,
    name: "Units",
    url: "/units",
    icon: <FaSquare />,
  },
  {
    id: 4,
    name: "Tab04",
    url: "/tab04",
    icon: <FaSquare />,
  },
];
